services:
  - type: web
    runtime: node
    name: fullstack-ml-portfolio-backend
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "465"
      - key: EMAIL_SECURE
        value: "true"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CONTACT_NOTIFY_TO
        sync: false
      - key: CONTACT_NOTIFY_FROM
        sync: false

  - type: web
    runtime: python
    name: fullstack-ml-portfolio-ml-service
    rootDir: ml-service
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: CORS_ORIGINS
        sync: false
